### ISSUE TITLE
SMAP isn't working: SMAP/audio/init.lua:287: bad argument #1 (number expected, got nil)

### ISSUE THREAD

**Issue by Peppernose145** [OpenPrograms/Fingercomp-Programs#12]
When I try to play any MIDI file, no matter what device I choose, it gives me this:

An error occurred: /usr/lib/SMAP/audio/init.lua:287: bad argument #1 (number expected, got nil)

**Comment by Fingercomp** [comment]
I have tried looking into the issue, but I have become completely lost in my own code. Looking back at it now, I can say that it is poorly written and has to be refactored. Unfortunately, I do not have an interest in performing a refactoring; moreover, for certain reasons, I am unable to test the program.

Therefore, I am afraid I have to close this issue.

To make it clear that I do not intend to maintain the package anymore, I have put a clear notice both in the smap's own README file and in the main README file as well as hidden the package from the package list.

---

I think you can use the following program as a substitute for the player (I could not test it, though). If it is saved as `smap-play.lua`, you should then run `smap-play file.nbs inoteblock` (replacing `file.nbs` with the path to the actual music file and `inoteblock` with the device name).

```lua
local smap = require("smap")

local path = assert(..., "This program needs a path to the music file")
local device = assert(select(2, ...), "This program needs a device name to play audio with (supported: inoteblock, pcspkr, beep)")

local music = smap.load(path, smap.guessFormat(path))
local outputDevice = smap.modules.output[device].new()
music:connect(outputDevice)
assert(music:play(math.huge))
```
