### ISSUE TITLE
net-flash problem

### ISSUE THREAD

**Issue by RockRaider2056** [OpenPrograms/Fingercomp-Programs#13]
I can't seem to get this program to work. I did some tests and found my setup working when sending messages from the lua prompt. I used
`component.modem.broadcast(1370, "net-eeprom", "eeprom", 1, "computer.beep()")`
and the drone beeped.
And now I'm a bit out of ideas because I don't see an apparent reason for the net-flash program to refuse to work.
Hope you can help me with this.

**Comment by Fingercomp** [comment]
Sorry for not responding for so long. I've totally forgotten about this issue. Anyway, it's fixed; thanks for reporting it.
