### ISSUE TITLE
Trees not detected.

### ISSUE THREAD

**Issue by DBevillJr** [OpenPrograms/Fingercomp-Programs#6]
Your "Lumber" code works great except that when the trees are grown it does not chop them down. I have tried several different axes and none are working.

**Comment by DBevillJr** [comment]
NVM, I didn't have a log in the slot next to the sapling.

**Comment by Fingercomp** [comment]
Suprisingly enough (I try to keep documentation as descriptive and up-to-date as possible), I haven't mentioned in the README that `lumber` needs saplings and a log to compare a block in front of robot with. Going to fix that.
