### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by ghost1257** [OpenPrograms/Fingercomp-Programs#7]
I can not get this program to work can you tell me what i am doing wrong I keep getting this error.  

![2017-08-16_12 49 03](https://user-images.githubusercontent.com/17717224/29374959-50bfc6b4-8281-11e7-8df4-088ca13d8cbe.png)

**Comment by Fingercomp** [comment]
You should at least mention what program you are talking about. Thankfully I've got a mail that contains a screenshot of `pastebin run https://github.com/OpenPrograms/Fingercomp-Programs/tree/master/eumon` typed in the shell.

Install either `oppm` (from the `oppm` floppy disk bundled with OpenComputers) or `hpm` and use one of them to install a package from OpenPrograms repositories. They automatically download all files and install dependencies. Don't copy-paste files.

As for the `eumon` program, you should run either `oppm install eumon` or `hpm oppm:install eumon`.
